openapi: "3.0.0"
info:
  title: Dummy API
  version: 1.0.0
  summary: An API to handle dummy requests
  description: |-
    Common tag is related to service status

tags:
  - name: common
    description: Common endpoints

paths:
  /health:
    get:
      operationId: HealthCheck
      summary: Returns OK if healthy.
      tags:
        - common
      responses:
        '200':
          content: {}
          description: OK.
        default:
          content: {}
          description: Unknown Error
  /:
    post:
      operationId: Request
      summary: Process a dummy request
      description: |-
        A dummy request contains an array of strings 
        and the service will reply with an array of 
        the reversed strings. 
      tags:
      requestBody:
        description: |-
          The byte encoded request.
          Encoded requests can be concatenated.
        required: true
        content:
          application/vnd.request+msgpack:
            schema:
              $ref: '#/components/schemas/Request'
            examples:
              '"Hello World"':
                summary: A single string, "Hello World"
                value: '[]'
              '"Hello"+"World"': 
                summary: Two strings, "Hello" and "World"
                value: '[]'
      responses:
        '200':
          description: |-
            The byte encoded response.
            For multiple responses, then encoded responses are concatenated.
          required: true
          content:
            application/vnd.response+msgpack:
              schema:
                $ref: '#/components/schemas/Response'
              examples:
                '"dlroW olleH"':
                  summary: A single reversed string of "Hello World"
                  value: '[]'
                '["olleH", "dlroW"]':
                  summary: Two revered strings of "Hello" and "World"
                  value: '[]'
        default:
          content: {}
          description: Unknown Error
components:
  parameters:
  schemas:
    'String':
      type: string
    'Request':
      $ref: '#/components/schemas/String'
    'Response':
      $ref: '#/components/schemas/String'
